### ISSUE TITLE
make bom searchable

### ISSUE THREAD

**Issue by keiser1080** [wagiminator/ATmega-Soldering-Station#10]
Hi, 
i just discover that github can make the csv & tsv file searchable.
It's automatic.
In order to make the bom searchable you have tu remove the double cote.

https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/rendering-csv-and-tsv-data
Thanks again for this project!

**Comment by wagiminator** [comment]
Hi,
thank you, it's great. The problem are not the quotation marks, I had to rename the file extensions from .csv to .tsv because the files are tab-seperated.
