### ISSUE TITLE
Grounding problem and 12V power supply compatibility

### ISSUE THREAD

**Issue by waitlamp** [wagiminator/ATmega-Soldering-Station#11]
Many DIY T12 Soldering Stations Use Switch Mode Power Supply. 
When use an ungrounded SMPS, Y Capacitor can conduct a 50 / 60 Hz AC to metal surface, usually the half of 220 V/ 110 V  voltage. Grounding is a  easy and effective way to avoid leakage current and circuit damage ( rarely occurs ), but in some cases grounding may not be feasible. ( e.g. buildings lack of PE line rarely ) 

#### I have heard many solutions such as:
+ Grounding to metal water pipe
+ Use a battery power supply hardware version
+ Use linear power supply
+ Use antistatic plastic floor
+ Use Isolation transformer

**some of them may not safe and useless*

After considering safety and price, I decided to try another way. Use a power bank provide the power to T12 soldering. When using specific cable accessories, QC protocol supported power bank can easily provided 12V voltage, when use a PD protocol supported power bank, it can be higher ( In fact, some hardware versions even use a MacBook power adaptor as power supply and casing of T12 soldering station ). especially the former is much cheaper than series battery packs, and more portable and removable. Connect with a power bank, T12 can be used as a portable soldering station. 
I found that some people have tested it on some commercial versions of the DIY T12 soldering station, and it works well except for a slightly longer heating time, even for some of the DC socket versions marked with 16-24 volts.

What about this soldering station?

The document requests power voltage 16V - 24V. Will it works properly at 12V?
If it can work, could you please add 12V power supply specification to the document?

thanks.

**Comment by wagiminator** [comment]
So far I have only tested the soldering station with 16 - 24V. Basically, it should also work with 12V, but then the power is only 18W. If, as you say, it also works with 12V with other T12 stations, then it should not be any different with this one, as it essentially depends on the soldering tip, not the soldering station. Anyway, if I find the time on the weekend, I'll test it out. If I can solder with 12V reasonably well, I will adapt the information in the description accordingly.
