### ISSUE TITLE
What is the role of the op amp on the right side of lmv358？

### ISSUE THREAD

**Issue by Eddddddddy** [wagiminator/ATmega-Soldering-Station#17]
I am trying to understand the right op amp. I don’t know why you design it like this. I'm really not good at this.
![IMG_0143](https://user-images.githubusercontent.com/46312408/126199650-ad01f8bb-d80e-46b3-8717-90488ead3dc3.jpeg)

**Comment by wagiminator** [comment]
Hi, the second OpAmp of the LMV358 is not used. An unused OpAmp should not float, as this can interfere with the OpAmps in use or, in the worst case, lead to its destruction. The two resistors stabilize the second OpAmp by forming a unity gain amplifier (or buffer) with VCC/2 as a fixed positive input value.

**Comment by Eddddddddy** [comment]
Thanks for this answer. I got it!

**Comment by Eddddddddy** [comment]
by the way. Can I use OPA333 replace LMV358? I rebuild the PCB project. OPA333 is much smaller than LMV358.

**Comment by wagiminator** [comment]
Yes, of course, that should work fine.

**Comment by Eddddddddy** [comment]
thanks！！
