### ISSUE TITLE
PID buzzing noises.

### ISSUE THREAD

**Issue by dahayer** [wagiminator/ATmega-Soldering-Station#29]
I have a strange buzzing noises (not from the buzzer) when using PID controlling, but  everything works like a charm.
I cannot find the responsible component. Any help will be appreciated. Thanks

**Comment by wagiminator** [comment]
Strange. Is the noise coming from the soldering station or another device nearby?

**Comment by dahayer** [comment]
Its from the soldering station i have recorded the noises with my phone if you want to hear it.
[https://drive.google.com/file/d/1bfbQFNnSnpNc9TIUcPRwxzufM4XHLMXw/view?usp=sharing](https://drive.google.com/file/d/1bfbQFNnSnpNc9TIUcPRwxzufM4XHLMXw/view?usp=sharing)

**Comment by wagiminator** [comment]
This could be one of the ceramic capacitors (singing capacitors phenomenon), possibly C7 or C13. You can try using capacitors with the same values but from different manufacturers, or change the PWM frequency in the code.

**Comment by dahayer** [comment]
I changed both C13 and C7 capacitors and the problem solved no more noises.
Thank you very much for your help.
