### ISSUE TITLE
Uncontrolled heating of the soldering iron head, power indicator flashing

### ISSUE THREAD

**Issue by LLC-zh** [wagiminator/ATmega-Soldering-Station#32]
When I solder the entire board and connect the 24v3a power supply, everything looks normal, but when I insert the soldering iron tip it goes black, the power indicator blinks, and the iron tip heats up. I don't understand why this is, I need help, thank you.

**Comment by LLC-zh** [comment]
To add, 12v1a is fine, just slow to heat up, but 24v3a still doesn't work.

**Comment by wagiminator** [comment]
I suspect that the power adapter is a bit overwhelmed at 3A and switches off temporarily, which would also explain the blinking of the power LED. You can check my theory with a multimeter: measure the input voltage at the station and see if the voltage fluctuates. If so, try a different power adapter.

**Comment by LLC-zh** [comment]
When the soldering station is unloaded I measured 24v on the lr7843, 5v on one end of the 78m05 and 24v on the other, 24v on the vin,no voltage on the P+. When I insert the soldering iron tip all the voltages become unstable.

**Comment by wagiminator** [comment]
So I think it's the power adapter. Do you have a lab bench power supply?

**Comment by LLC-zh** [comment]
Yes,you are right,I bought a new power adaptor,it worked fine,thank you again.

**Comment by wagiminator** [comment]
Great!
